stages:
  - build-base
  - test
  - build
  - push
  - deploy-dev
  - deploy-prod

variables:
  DOCKER_REGISTRY: "harbor-ai.clicknext.com/poc"
  DOCKER_IMAGE_NAME: trd-adaptor
  DOCKER_REG_IMAGE: $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME
  APP_NAME: trd-adaptor

services:
  - docker:dind

docker-build-base:
  stage: build-base
  tags:
    - docker-deploy
  only:
    changes:
      - Dockerfile.base
      - requirements.txt
  before_script:
    - docker login -u $harUser -p $harPass harbor-ai.clicknext.com
  script:
    - docker build -t $DOCKER_REG_IMAGE:base -f Dockerfile.base .
    - docker push $DOCKER_REG_IMAGE:base

docker-build:
  stage: build
  tags:
    - docker-deploy
  only:
    - uat
    - main
    - /^v\d+\.\d+\.\d+$/
    - tags
  before_script:
    - docker login -u $harUser -p $harPass harbor-ai.clicknext.com
  script:
    - |

      # UAT
      if [ "$CI_COMMIT_REF_NAME" = "uat" ]; then
        docker build -t $DOCKER_REG_IMAGE-uat:latest \
          -t $DOCKER_REG_IMAGE-uat:$CI_COMMIT_SHORT_SHA \
          -f Dockerfile.app .

      # PROD
      elif [ "$CI_COMMIT_TAG" ]; then
        docker build -t $DOCKER_REG_IMAGE-prod:latest \
          -t $DOCKER_REG_IMAGE-prod:$CI_COMMIT_TAG \
          -f Dockerfile.app .

      # DEV
      elif [ "$CI_COMMIT_REF_NAME" = "main" ]; then
        docker build -t $DOCKER_REG_IMAGE-dev:latest \
          -t $DOCKER_REG_IMAGE-dev:$CI_COMMIT_SHORT_SHA \
          -f Dockerfile.app .
      fi

docker-push:
  stage: push
  tags:
    - docker-deploy
  only:
    - uat
    - main
    - /^v\d+\.\d+\.\d+$/
    - tags
  dependencies:
    - "docker-build"
  before_script:
    - docker login -u $harUser -p $harPass harbor-ai.clicknext.com
  script:
    - |

      # UAT
      if [ "$CI_COMMIT_REF_NAME" = "uat" ]; then
        docker push $DOCKER_REG_IMAGE-uat:latest
        docker push $DOCKER_REG_IMAGE-uat:$CI_COMMIT_SHORT_SHA

      # PROD
      elif [ "$CI_COMMIT_TAG" ]; then
        docker push $DOCKER_REG_IMAGE-prod:latest
        docker push $DOCKER_REG_IMAGE-prod:$CI_COMMIT_TAG

      # DEV
      elif [ "$CI_COMMIT_REF_NAME" = "main" ]; then
        docker push $DOCKER_REG_IMAGE-dev:latest
        docker push $DOCKER_REG_IMAGE-dev:$CI_COMMIT_SHORT_SHA
      fi

dev:
  stage: deploy-dev
  tags:
    - docker-deploy
  only:
    - main
  dependencies:
    - "docker-push"
  before_script:
    - docker login -u $harUser -p $harPass harbor-ai.clicknext.com
  script:
    - |

      docker rm -f $APP_NAME || true

      docker run -d --name $APP_NAME --restart always \
          -p 8089:8000 \
          -e RELEASE_VERSION="DEV" \
          -e  OPENAI_API_KEY="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" \
          -e CHATBOT_API_KEY="CN_CB_API_KEY:158f7ac1-8f18-42a5-ac68-fd16d1a604ef" \
          -e CHANNEL_ACCESS_TOKEN="q5iS+Dt3PUc2MZ3HEjs7F8VA28qepXUQLzhl4boNtJirVon52Ye+UeXbJ8Ijk4Op4gZTvPkQnJzJfQwBuS7kFt6dymGYK1Buz7icZ/kyIcd16NBPU9QqleMTV9uaZE0uxIJOhqVUbOma66jvghwD9QdB04t89/1O/w1cDnyilFU="  \
          -e CHANNEL_SECRET="8e93b4591d8b15d8f4e1de5c2be892a7" \
          -w /trd_adaptor \
          $DOCKER_REG_IMAGE-dev:$CI_COMMIT_SHORT_SHA \
          python3 main.py