FROM ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    curl ca-certificates sudo git bzip2 \
    libx11-6 vim build-essential screen \
    python3 python3-pip libmagic-dev \
    software-properties-common xvfb \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --upgrade pip
WORKDIR /trd_adaptor
COPY requirements.txt .
RUN pip install --root-user-action=ignore --ignore-installed -r requirements.txt
